spring:
  application:
    name: zuul-edge-server
eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

server:
  port: 8762

zuul:
  routes:
    product:
      path: /api/**
      service-id: product-service
      strip-prefix: false